### ISSUE TITLE
Failed to Login

### ISSUE THREAD

**Issue by wc311** [icholy/r2i_bot#3]
Getting the error 
failed to login: fail: challenge_required (checkpoint_challenge_required)

**Comment by wc311** [comment]
Yeah, its a problem in regards to instagram requiring an sms/email verification on login due to "suspicious activity." Dont really know how I would fix that in regards to the code, but Im going to try a trick where you temporaryly disable your account for 3 hours and then login to it.

**Comment by icholy** [comment]
You probably got throttled for posting too much

**Comment by wc311** [comment]
Yeah temporarily disabling my account for a couple hours fixed the login error. 
Just in case anyone encounters this issue to disable your account: open your account through instas web based app, go to edit profile, scroll down and click the button "temporarily disable account" and for reason just say "I needed a break" and then after a couple hours just run the bot and make sure to not login anywhere else before running the bot.
